1번
SELECT *
FROM emp;
2번
SELECT *
FROM emp
WHERE DEPTNO = 30 AND JOB = 'SALESMAN';
3번
SELECT *
FROM emp
WHERE SAL BETWEEN 2000 AND 3000;
4번
CREATE TABLE EMP_TEMP AS
SELECT * FROM EMP WHERE 1 != 1;

DESCRIBE EMP_TEMP;
5번
INSERT INTO EMP_TEMP
VALUES(9999, '홍길동', 'PRESIDENT', NULL, TO_DATE('2001/01/01'), 5000, 1000, 10);
6번
CREATE TABLE DEPT_TEMP2 AS
SELECT * FROM DEPT;

DESCRIBE DEPT_TEMP2;
7번
UPDATE DEPT_TEMP2
SET DNAME = 'DATABASE', LOC = 'SEOUL'
WHERE DEPTNO = 40;

SELECT *
FROM DEPT_TEMP2;

8번
ROLLBACK;
9번
SELECT *
FROM EMP
WHERE UPPER(ENAME) = 'SMITH';  
10번
SELECT *
FROM EMP
WHERE LENGTH(ENAME) <= 4;
11번
SELECT SUBSTR(JOB,1,3)
FROM EMP;
12번
SELECT *
FROM EMP
WHERE HIREDATE >= TO_DATE('1981/06/01');
13번
SELECT EMPNO, ENAME, SAL, NVL(COMM,0), (SAL*12)+NVL(COMM,0) ANNSAL
FROM EMP;
14번
SELECT COUNT(DISTINCT(JOB))
FROM EMP;
15번
SELECT e.ENAME, d.DNAME
FROM EMP e
JOIN DEPT d ON e.DEPTNO = d.DEPTNO
WHERE SAL >= 3000;

SELECT *
FROM DEPT;

16번 
SELECT *
FROM EMP
WHERE SAL < ( SELECT SAL FROM EMP WHERE ENAME = 'MARTIN');
17번
SELECT *
FROM EMP
WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE DEPTNO = 30);
18번
SELECT *
FROM EMP E
JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.JISAL
WHERE S.GRADE = 3 AND DEPTNO=30);

19번
CREATE TABLE EMP_DDL (
    EMPNO       NUMBER(4),
    ENAME       VARCHAR2(10),
    JOB         VARCHAR2(9),
    MGR         NUMBER(4),
    HIREDATE    DATE,
    SAL         NUMBER(7,2),
    COMM        NUMBER(7,2),
    DEPTNO      NUMBER(2)
    );
    
    
DESCRIBE EMP_DDL;

